name: Updater

on:
  workflow_run:
    workflows:
      - TypeScript compilation
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Setup key
        env:
          SSH_KEY: ${{ secrets.KEY }}
        run: |
          echo "$SSH_KEY" > $HOME/ssh-key
          chmod 400 $HOME/ssh-key
      - name: Synchronize server's code
        env:
          DIRECTORY: ${{ secrets.DIRECTORY }}
        run: ssh -i $HOME/ssh-key -o "StrictHostKeyChecking=no" ${{ secrets.USERNAME }}@${{ secrets.HOST }} "pm2 restart TrojanerBot"